version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: collaborative-postgres
    environment:
      POSTGRES_DB: collaborative_review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - collaborative-network

  # MongoDB for chat and review data
  mongodb:
    image: mongo:7.0
    container_name: collaborative-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: collaborative
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - collaborative-network

  # Redis for caching and pub/sub
  redis:
    image: redis:7-alpine
    container_name: collaborative-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - collaborative-network

  # ClickHouse for analytics
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: collaborative-clickhouse
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./infrastructure/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - collaborative-network

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:10.2.0
    container_name: collaborative-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - collaborative-network
    depends_on:
      - clickhouse

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: collaborative-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - collaborative-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  clickhouse_data:
  grafana_data:
  prometheus_data:

networks:
  collaborative-network:
    driver: bridge 